# Generated by Django 5.1.1 on 2024-10-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos_restaurante', '0001_initial'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacion',
            name='restaurante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Datos_restaurante.configuracion'),
        ),
    ]
