# Generated by Django 5.1.1 on 2024-10-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_facturacion_restaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacion',
            name='total_a_pagar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
