# Generated by Django 5.1.1 on 2024-10-22 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Datos_restaurante', '0001_initial'),
        ('facturacion', '0003_facturacion_total_a_pagar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Configuracion',
            new_name='Configuraciones',
        ),
    ]
